language: go

go:
  - 1.8
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - rm -rf $GOPATH/src/gopkg.in/src-d
  - mkdir -p $GOPATH/src/gopkg.in/src-d
  - ln -s $PWD $GOPATH/src/gopkg.in/src-d/enry.v1
  - cd $GOPATH/src/gopkg.in/src-d/enry.v1
  - go get -v -t ./...

script:
  - make test-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - make packages

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file_glob: true
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true

jobs:
  include:
    - stage: test
      language: scala
      jdk: oraclejdk8

      install:
        - GIMME_OUTPUT=$(gimme 1.8 | tee -a $HOME/.bashrc) && eval "$GIMME_OUTPUT"
        - export GOPATH=$HOME/gopath
        - mkdir -p $GOPATH/src/gopkg.in/src-d/enry.v1
        - rsync -az ${TRAVIS_BUILD_DIR}/ $GOPATH/src/gopkg.in/src-d/enry.v1
        - go get -v gopkg.in/src-d/enry.v1/...

      before_script:
        - cd java
        - make

      script:
        - make test

      before_deploy:
        - cd ..

      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file:
          - ./.shared/linux-x86-64/libenry.so
        skip_cleanup: true
        on:
          tags: true

    - stage: test
      language: scala
      os: osx
      osx_image: xcode8.3

      install:
        - GIMME_OUTPUT=$(gimme 1.8 | tee -a $HOME/.bashrc) && eval "$GIMME_OUTPUT"
        - export GOPATH=$HOME/gopath
        - mkdir -p $GOPATH/src/gopkg.in/src-d/enry.v1
        - rsync -az ${TRAVIS_BUILD_DIR}/ $GOPATH/src/gopkg.in/src-d/enry.v1
        - go get -v gopkg.in/src-d/enry.v1/...

      before_script:
        - cd java
        - make

      script:
        - make test

      before_deploy:
        - make os-shared-lib
        - cd ..

      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file: ./.shared/darwin/libenry.dylib
        skip_cleanup: true
        on:
          tags: true

    - stage: publishmaven
      language: scala
      jdk: oraclejdk8

      before_script:
        - cd java
        - make
        - curl -o ./shared/linux-x86-64/libenry.so -sL "https://github.com/$TRAVIS_REPO_SLUG/releases/download/$TRAVIS_TAG/libenry.so"
        - openssl aes-256-cbc -K $encrypted_58e1643233d2_key -iv $encrypted_58e1643233d2_iv -in key.asc.enc -out key.asc -d
        - gpg --no-default-keyring --primary-keyring ./project/.gnupg/pubring.gpg --secret-keyring ./project/.gnupg/secring.gpg --keyring ./project/.gnupg/pubring.gpg --fingerprint --import key.asc

      script:
        - make test # ensure the shared objects are functional
        - ./sbt publishLocal
        - ./sbt publishSigned

      before_deploy:
        - rm ./target/enry-java-*-javadoc.jar
        - rm ./target/enry-java-*-sources.jar
        - rm ./target/enry-java-*-tests.jar
        - rm ./target/enry-java-assembly-*.jar

      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file_glob: true
        file: ./target/enry-java*.jar
        skip_cleanup: true
        on:
          tags: true
